server.port=8080

# logging
logging.level.com.ssafy=debug

spring.devtools.livereload.enabled=true
spring.devtools.remote.restart.enabled=true

spring.servlet.multipart.maxFileSize=50MB
spring.servlet.multipart.maxRequestSize=50MB

# must ends with '/'
uploadPath: C:/Temp/upload/

